export const GAME_COMMAND_TYPE = Object.freeze({
  MATCH_STARTED: "MATCH_STARTED",
  MATCH_RESTARTED: "MATCH_RESTARTED",
  SHOT_STARTED: "SHOT_STARTED",
  SHOT_TARGET_SELECTED: "SHOT_TARGET_SELECTED",
  SHOT_ROUTE_CONFIRMED: "SHOT_ROUTE_CONFIRMED",
  SHOT_RESOLUTION_DUE: "SHOT_RESOLUTION_DUE",
  SHOT_CONSEQUENCE_DUE: "SHOT_CONSEQUENCE_DUE",
  SHOT_CANCELLED: "SHOT_CANCELLED",
  PASS_STARTED: "PASS_STARTED",
  PASS_TARGET_SELECTED: "PASS_TARGET_SELECTED",
  PASS_ROUTE_CONFIRMED: "PASS_ROUTE_CONFIRMED",
  PASS_INTERCEPTOR_SELECTED: "PASS_INTERCEPTOR_SELECTED",
  PASS_INTERCEPTION_ROLL_SUBMITTED: "PASS_INTERCEPTION_ROLL_SUBMITTED",
  GAMEPLAY_ROLL_SUBMITTED: "GAMEPLAY_ROLL_SUBMITTED",
  PASS_INTERCEPTION_RESOLUTION_DUE: "PASS_INTERCEPTION_RESOLUTION_DUE",
  PASS_CONSEQUENCE_DUE: "PASS_CONSEQUENCE_DUE",
  PASS_CANCELLED: "PASS_CANCELLED",
  THROUGH_BALL_STARTED: "THROUGH_BALL_STARTED",
  THROUGH_BALL_TARGET_SELECTED: "THROUGH_BALL_TARGET_SELECTED",
  THROUGH_BALL_COMMITTED: "THROUGH_BALL_COMMITTED",
  THROUGH_BALL_CANCELLED: "THROUGH_BALL_CANCELLED",
  THROUGH_BALL_RECOVERER_SELECTED: "THROUGH_BALL_RECOVERER_SELECTED",
  THROUGH_BALL_RECOVERY_CONFIRMED: "THROUGH_BALL_RECOVERY_CONFIRMED",
  LOFTED_THROUGH_BALL_STARTED: "LOFTED_THROUGH_BALL_STARTED",
  LOFTED_THROUGH_BALL_TARGET_SELECTED: "LOFTED_THROUGH_BALL_TARGET_SELECTED",
  LOFTED_THROUGH_BALL_COMMITTED: "LOFTED_THROUGH_BALL_COMMITTED",
  LOFTED_THROUGH_BALL_CANCELLED: "LOFTED_THROUGH_BALL_CANCELLED",
  LOFTED_THROUGH_BALL_ROLL_SUBMITTED: "LOFTED_THROUGH_BALL_ROLL_SUBMITTED",
  LOFTED_THROUGH_BALL_RESOLUTION_DUE: "LOFTED_THROUGH_BALL_RESOLUTION_DUE",
  LOFTED_THROUGH_BALL_RESOLUTION_CONFIRMED: "LOFTED_THROUGH_BALL_RESOLUTION_CONFIRMED",
  LOFTED_THROUGH_BALL_RECOVERER_SELECTED: "LOFTED_THROUGH_BALL_RECOVERER_SELECTED",
  LOFTED_THROUGH_BALL_RECOVERY_CONFIRMED: "LOFTED_THROUGH_BALL_RECOVERY_CONFIRMED",
  EXTRA_ROLL_SUBMITTED: "EXTRA_ROLL_SUBMITTED",
  FREE_BALL_MOVED: "FREE_BALL_MOVED",
  NORMAL_MOVE_STARTED: "NORMAL_MOVE_STARTED",
  NORMAL_MOVE_CANCELLED: "NORMAL_MOVE_CANCELLED",
  NORMAL_MOVE_COMMITTED: "NORMAL_MOVE_COMMITTED",
  BONUS_MOVE_STARTED: "BONUS_MOVE_STARTED",
  BONUS_MOVE_CANCELLED: "BONUS_MOVE_CANCELLED",
  BONUS_MOVE_COMMITTED: "BONUS_MOVE_COMMITTED",
  BONUS_ACTION_ENDED: "BONUS_ACTION_ENDED",
  TRACKER_PHASE_ENDED: "TRACKER_PHASE_ENDED",
  THREE_TWO_MOVE_COMMITTED: "THREE_TWO_MOVE_COMMITTED",
  FREE_MOVE_STARTED: "FREE_MOVE_STARTED",
  FREE_MOVE_COMMITTED: "FREE_MOVE_COMMITTED",
  FREE_MOVE_ENDED: "FREE_MOVE_ENDED",
  GROUP_MOVE_ZONE_CONFIRMED: "GROUP_MOVE_ZONE_CONFIRMED",
  GROUP_MOVE_PLAYER_COMMITTED: "GROUP_MOVE_PLAYER_COMMITTED",
  PIECE_ACTIVITY_CHANGED: "PIECE_ACTIVITY_CHANGED",
  TRACKER_ACTIONS_RESET: "TRACKER_ACTIONS_RESET",
  TRACKER_POSSESSION_CHANGED: "TRACKER_POSSESSION_CHANGED",
  MANUAL_ACTION_DECLARED: "MANUAL_ACTION_DECLARED",
  BONUS_MANUAL_ACTION_DECLARED: "BONUS_MANUAL_ACTION_DECLARED",
  FORMATION_TACTIC_CONFIRMED: "FORMATION_TACTIC_CONFIRMED",
  ADJUST_PIECE_PLACED: "ADJUST_PIECE_PLACED",
  KICKOFF_READY_CONFIRMED: "KICKOFF_READY_CONFIRMED",
  RESTART_WALL_POSITION_SET: "RESTART_WALL_POSITION_SET",
  RESTART_WALL_SET: "RESTART_WALL_SET",
  RESTART_PIECE_REPOSITIONED: "RESTART_PIECE_REPOSITIONED",
  RESTART_REPOSITION_PASSED: "RESTART_REPOSITION_PASSED",
  RESTART_EXECUTOR_SELECTED: "RESTART_EXECUTOR_SELECTED",
  RESTART_WALL_CONTINUATION_CONFIRMED: "RESTART_WALL_CONTINUATION_CONFIRMED",
  RESTART_WALL_CONTINUATION_DECLINED: "RESTART_WALL_CONTINUATION_DECLINED",
  GK_REPOSITION_PIECE_SELECTED: "GK_REPOSITION_PIECE_SELECTED",
  GK_REPOSITION_MOVE_COMMITTED: "GK_REPOSITION_MOVE_COMMITTED",
  GK_REPOSITION_TURN_ENDED: "GK_REPOSITION_TURN_ENDED",
  MARKING_ACCEPTED: "MARKING_ACCEPTED",
  MARKING_DECLINED: "MARKING_DECLINED",
  MARKING_TRACK_MOVE_COMMITTED: "MARKING_TRACK_MOVE_COMMITTED",
  MARKING_CONTINUE_ACCEPTED: "MARKING_CONTINUE_ACCEPTED",
  MARKING_CONTINUE_DECLINED: "MARKING_CONTINUE_DECLINED",
  MARKING_TRACK_CANCELED: "MARKING_TRACK_CANCELED",
  MARKING_SWITCH_ACCEPTED: "MARKING_SWITCH_ACCEPTED",
  MARKING_SWITCH_DECLINED: "MARKING_SWITCH_DECLINED",
  TACKLING_STARTED: "TACKLING_STARTED",
  TACKLING_NOTICE_ACKNOWLEDGED: "TACKLING_NOTICE_ACKNOWLEDGED",
  TACKLING_RESOLUTION_DUE: "TACKLING_RESOLUTION_DUE",
  TACKLING_CONSEQUENCE_DUE: "TACKLING_CONSEQUENCE_DUE",
  OFFSIDE_RESTART_CONFIRMED: "OFFSIDE_RESTART_CONFIRMED",
});

function clonePayload(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return {};
  return typeof structuredClone === "function"
    ? structuredClone(value)
    : JSON.parse(JSON.stringify(value));
}

export function normalizeGameCommand(raw = {}) {
  return {
    id: String(raw?.id || "").trim(),
    type: String(raw?.type || "").trim(),
    payload: clonePayload(raw?.payload),
  };
}

export function gameCommandValidationReason(command) {
  if (!command?.id) return "COMMAND_ID_REQUIRED";
  if (!command?.type) return "COMMAND_TYPE_REQUIRED";
  return null;
}
